### ISSUE TITLE
Use config file instead of go file

### ISSUE THREAD

**Issue by v1rtl** [geremachek/catfm#1]
Would be nicer to parse config instead of writing it before building.

My preference is TOML.

I'll try to make a PR with using a configuration file

**Comment by Leguu** [comment]
Reading and parsing a config file will always take time when launching the program. Having the settings built into the code when compiled is faster. In any case, changing configurations doesn't occur often enough for a file manager for this to be a big issue, whereas a separate config file has to be read every time the program is launched.

**Comment by v1rtl** [comment]
@Leguu

config is more convenient to share, easier to write

if config is small, it won't be parsed for a long time.

config may not be changed often but I don't want to recompile the whole app just because I want to edit one param in a config
